version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/adminui"
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: "/minimalcss"
  schedule:
    interval: weekly
