# http://travis-ci.org/peterbe/django-peterbecom

# Needed to install custom java and elasticsearch
sudo: required

dist: trusty

services:
  - postgresql

language: python

cache: pip

python: 3.5

branches:
  only:
  - master

addons:
  postgresql: "9.5"
  apt:
    packages:
      - oracle-java9-set-default

before_install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.1.deb && sudo service elasticsearch start
  - psql -V
  - psql -c 'create database peterbecom;' -U postgres
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - sudo apt-get -y update && sudo apt-get -y install nodejs
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn --version

install:
  - bin/travis/install.sh

before_script:
  - bin/travis/lint.sh
  - bin/travis/setup.sh

script:
  - bin/travis/test.sh
